/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../../common";

export declare namespace IExecution {
  export type ExecutionStruct = {
    target: PromiseOrValue<string>;
    value: PromiseOrValue<BigNumberish>;
    callData: PromiseOrValue<BytesLike>;
  };

  export type ExecutionStructOutput = [string, BigNumber, string] & {
    target: string;
    value: BigNumber;
    callData: string;
  };
}

export interface IMSAInterface extends utils.Interface {
  functions: {
    "execute(address,uint256,bytes)": FunctionFragment;
    "executeBatch((address,uint256,bytes)[])": FunctionFragment;
    "executeBatchFromExecutor((address,uint256,bytes)[])": FunctionFragment;
    "executeDelegateCall(address,bytes)": FunctionFragment;
    "executeDelegateCallFromExecutor(address,bytes)": FunctionFragment;
    "executeFromExecutor(address,uint256,bytes)": FunctionFragment;
    "initializeAccount(bytes)": FunctionFragment;
    "installExecutor(address,bytes)": FunctionFragment;
    "installFallback(address,bytes)": FunctionFragment;
    "installValidator(address,bytes)": FunctionFragment;
    "isExecutorInstalled(address)": FunctionFragment;
    "isFallbackInstalled(address)": FunctionFragment;
    "isValidatorInstalled(address)": FunctionFragment;
    "uninstallExecutor(address,bytes)": FunctionFragment;
    "uninstallFallback(address,bytes)": FunctionFragment;
    "uninstallValidator(address,bytes)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "execute"
      | "executeBatch"
      | "executeBatchFromExecutor"
      | "executeDelegateCall"
      | "executeDelegateCallFromExecutor"
      | "executeFromExecutor"
      | "initializeAccount"
      | "installExecutor"
      | "installFallback"
      | "installValidator"
      | "isExecutorInstalled"
      | "isFallbackInstalled"
      | "isValidatorInstalled"
      | "uninstallExecutor"
      | "uninstallFallback"
      | "uninstallValidator"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "execute",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "executeBatch",
    values: [IExecution.ExecutionStruct[]]
  ): string;
  encodeFunctionData(
    functionFragment: "executeBatchFromExecutor",
    values: [IExecution.ExecutionStruct[]]
  ): string;
  encodeFunctionData(
    functionFragment: "executeDelegateCall",
    values: [PromiseOrValue<string>, PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "executeDelegateCallFromExecutor",
    values: [PromiseOrValue<string>, PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "executeFromExecutor",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "initializeAccount",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "installExecutor",
    values: [PromiseOrValue<string>, PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "installFallback",
    values: [PromiseOrValue<string>, PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "installValidator",
    values: [PromiseOrValue<string>, PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "isExecutorInstalled",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "isFallbackInstalled",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "isValidatorInstalled",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "uninstallExecutor",
    values: [PromiseOrValue<string>, PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "uninstallFallback",
    values: [PromiseOrValue<string>, PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "uninstallValidator",
    values: [PromiseOrValue<string>, PromiseOrValue<BytesLike>]
  ): string;

  decodeFunctionResult(functionFragment: "execute", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "executeBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeBatchFromExecutor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeDelegateCall",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeDelegateCallFromExecutor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeFromExecutor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "initializeAccount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "installExecutor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "installFallback",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "installValidator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isExecutorInstalled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isFallbackInstalled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isValidatorInstalled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "uninstallExecutor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "uninstallFallback",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "uninstallValidator",
    data: BytesLike
  ): Result;

  events: {
    "DisableExecutor(address)": EventFragment;
    "DisableValidator(address)": EventFragment;
    "EnableExecutor(address)": EventFragment;
    "EnableValidator(address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "DisableExecutor"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "DisableValidator"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "EnableExecutor"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "EnableValidator"): EventFragment;
}

export interface DisableExecutorEventObject {
  module: string;
}
export type DisableExecutorEvent = TypedEvent<
  [string],
  DisableExecutorEventObject
>;

export type DisableExecutorEventFilter = TypedEventFilter<DisableExecutorEvent>;

export interface DisableValidatorEventObject {
  module: string;
}
export type DisableValidatorEvent = TypedEvent<
  [string],
  DisableValidatorEventObject
>;

export type DisableValidatorEventFilter =
  TypedEventFilter<DisableValidatorEvent>;

export interface EnableExecutorEventObject {
  module: string;
}
export type EnableExecutorEvent = TypedEvent<
  [string],
  EnableExecutorEventObject
>;

export type EnableExecutorEventFilter = TypedEventFilter<EnableExecutorEvent>;

export interface EnableValidatorEventObject {
  module: string;
}
export type EnableValidatorEvent = TypedEvent<
  [string],
  EnableValidatorEventObject
>;

export type EnableValidatorEventFilter = TypedEventFilter<EnableValidatorEvent>;

export interface IMSA extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IMSAInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    execute(
      target: PromiseOrValue<string>,
      value: PromiseOrValue<BigNumberish>,
      callData: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    executeBatch(
      executions: IExecution.ExecutionStruct[],
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    executeBatchFromExecutor(
      executions: IExecution.ExecutionStruct[],
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    executeDelegateCall(
      target: PromiseOrValue<string>,
      callData: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    executeDelegateCallFromExecutor(
      target: PromiseOrValue<string>,
      callData: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    executeFromExecutor(
      target: PromiseOrValue<string>,
      value: PromiseOrValue<BigNumberish>,
      callData: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    initializeAccount(
      data: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    installExecutor(
      executor: PromiseOrValue<string>,
      data: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    installFallback(
      fallbackHandler: PromiseOrValue<string>,
      data: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    installValidator(
      validator: PromiseOrValue<string>,
      data: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    isExecutorInstalled(
      executor: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    isFallbackInstalled(
      fallbackHandler: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    isValidatorInstalled(
      validator: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    uninstallExecutor(
      executor: PromiseOrValue<string>,
      data: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    uninstallFallback(
      fallbackHandler: PromiseOrValue<string>,
      data: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    uninstallValidator(
      validator: PromiseOrValue<string>,
      data: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  execute(
    target: PromiseOrValue<string>,
    value: PromiseOrValue<BigNumberish>,
    callData: PromiseOrValue<BytesLike>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  executeBatch(
    executions: IExecution.ExecutionStruct[],
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  executeBatchFromExecutor(
    executions: IExecution.ExecutionStruct[],
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  executeDelegateCall(
    target: PromiseOrValue<string>,
    callData: PromiseOrValue<BytesLike>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  executeDelegateCallFromExecutor(
    target: PromiseOrValue<string>,
    callData: PromiseOrValue<BytesLike>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  executeFromExecutor(
    target: PromiseOrValue<string>,
    value: PromiseOrValue<BigNumberish>,
    callData: PromiseOrValue<BytesLike>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  initializeAccount(
    data: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  installExecutor(
    executor: PromiseOrValue<string>,
    data: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  installFallback(
    fallbackHandler: PromiseOrValue<string>,
    data: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  installValidator(
    validator: PromiseOrValue<string>,
    data: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  isExecutorInstalled(
    executor: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  isFallbackInstalled(
    fallbackHandler: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  isValidatorInstalled(
    validator: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  uninstallExecutor(
    executor: PromiseOrValue<string>,
    data: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  uninstallFallback(
    fallbackHandler: PromiseOrValue<string>,
    data: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  uninstallValidator(
    validator: PromiseOrValue<string>,
    data: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    execute(
      target: PromiseOrValue<string>,
      value: PromiseOrValue<BigNumberish>,
      callData: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>;

    executeBatch(
      executions: IExecution.ExecutionStruct[],
      overrides?: CallOverrides
    ): Promise<string[]>;

    executeBatchFromExecutor(
      executions: IExecution.ExecutionStruct[],
      overrides?: CallOverrides
    ): Promise<string[]>;

    executeDelegateCall(
      target: PromiseOrValue<string>,
      callData: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>;

    executeDelegateCallFromExecutor(
      target: PromiseOrValue<string>,
      callData: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>;

    executeFromExecutor(
      target: PromiseOrValue<string>,
      value: PromiseOrValue<BigNumberish>,
      callData: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>;

    initializeAccount(
      data: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    installExecutor(
      executor: PromiseOrValue<string>,
      data: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    installFallback(
      fallbackHandler: PromiseOrValue<string>,
      data: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    installValidator(
      validator: PromiseOrValue<string>,
      data: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    isExecutorInstalled(
      executor: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    isFallbackInstalled(
      fallbackHandler: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    isValidatorInstalled(
      validator: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    uninstallExecutor(
      executor: PromiseOrValue<string>,
      data: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    uninstallFallback(
      fallbackHandler: PromiseOrValue<string>,
      data: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    uninstallValidator(
      validator: PromiseOrValue<string>,
      data: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "DisableExecutor(address)"(module?: null): DisableExecutorEventFilter;
    DisableExecutor(module?: null): DisableExecutorEventFilter;

    "DisableValidator(address)"(module?: null): DisableValidatorEventFilter;
    DisableValidator(module?: null): DisableValidatorEventFilter;

    "EnableExecutor(address)"(module?: null): EnableExecutorEventFilter;
    EnableExecutor(module?: null): EnableExecutorEventFilter;

    "EnableValidator(address)"(module?: null): EnableValidatorEventFilter;
    EnableValidator(module?: null): EnableValidatorEventFilter;
  };

  estimateGas: {
    execute(
      target: PromiseOrValue<string>,
      value: PromiseOrValue<BigNumberish>,
      callData: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    executeBatch(
      executions: IExecution.ExecutionStruct[],
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    executeBatchFromExecutor(
      executions: IExecution.ExecutionStruct[],
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    executeDelegateCall(
      target: PromiseOrValue<string>,
      callData: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    executeDelegateCallFromExecutor(
      target: PromiseOrValue<string>,
      callData: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    executeFromExecutor(
      target: PromiseOrValue<string>,
      value: PromiseOrValue<BigNumberish>,
      callData: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    initializeAccount(
      data: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    installExecutor(
      executor: PromiseOrValue<string>,
      data: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    installFallback(
      fallbackHandler: PromiseOrValue<string>,
      data: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    installValidator(
      validator: PromiseOrValue<string>,
      data: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    isExecutorInstalled(
      executor: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isFallbackInstalled(
      fallbackHandler: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isValidatorInstalled(
      validator: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    uninstallExecutor(
      executor: PromiseOrValue<string>,
      data: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    uninstallFallback(
      fallbackHandler: PromiseOrValue<string>,
      data: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    uninstallValidator(
      validator: PromiseOrValue<string>,
      data: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    execute(
      target: PromiseOrValue<string>,
      value: PromiseOrValue<BigNumberish>,
      callData: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    executeBatch(
      executions: IExecution.ExecutionStruct[],
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    executeBatchFromExecutor(
      executions: IExecution.ExecutionStruct[],
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    executeDelegateCall(
      target: PromiseOrValue<string>,
      callData: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    executeDelegateCallFromExecutor(
      target: PromiseOrValue<string>,
      callData: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    executeFromExecutor(
      target: PromiseOrValue<string>,
      value: PromiseOrValue<BigNumberish>,
      callData: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    initializeAccount(
      data: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    installExecutor(
      executor: PromiseOrValue<string>,
      data: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    installFallback(
      fallbackHandler: PromiseOrValue<string>,
      data: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    installValidator(
      validator: PromiseOrValue<string>,
      data: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    isExecutorInstalled(
      executor: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isFallbackInstalled(
      fallbackHandler: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isValidatorInstalled(
      validator: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    uninstallExecutor(
      executor: PromiseOrValue<string>,
      data: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    uninstallFallback(
      fallbackHandler: PromiseOrValue<string>,
      data: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    uninstallValidator(
      validator: PromiseOrValue<string>,
      data: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
