/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IAccountConfig_Hook,
  IAccountConfig_HookInterface,
} from "../../../../../src/ERC7579/interfaces/IEtherspotWallet7579.sol/IAccountConfig_Hook";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "module",
        type: "address",
      },
    ],
    name: "DisableHook",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "module",
        type: "address",
      },
    ],
    name: "EnableHook",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "hook",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "installHook",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "hook",
        type: "address",
      },
    ],
    name: "isHookInstalled",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "hook",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "uninstallHook",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IAccountConfig_Hook__factory {
  static readonly abi = _abi;
  static createInterface(): IAccountConfig_HookInterface {
    return new utils.Interface(_abi) as IAccountConfig_HookInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IAccountConfig_Hook {
    return new Contract(address, _abi, signerOrProvider) as IAccountConfig_Hook;
  }
}
