/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IExecutionUnsafe,
  IExecutionUnsafeInterface,
} from "../../../../../src/ERC7579/interfaces/IEtherspotWallet7579.sol/IExecutionUnsafe";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "target",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "callData",
        type: "bytes",
      },
    ],
    name: "executeDelegateCall",
    outputs: [
      {
        internalType: "bytes",
        name: "result",
        type: "bytes",
      },
    ],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "target",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "callData",
        type: "bytes",
      },
    ],
    name: "executeDelegateCallFromExecutor",
    outputs: [
      {
        internalType: "bytes",
        name: "result",
        type: "bytes",
      },
    ],
    stateMutability: "payable",
    type: "function",
  },
] as const;

export class IExecutionUnsafe__factory {
  static readonly abi = _abi;
  static createInterface(): IExecutionUnsafeInterface {
    return new utils.Interface(_abi) as IExecutionUnsafeInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IExecutionUnsafe {
    return new Contract(address, _abi, signerOrProvider) as IExecutionUnsafe;
  }
}
