/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as universalSignatureValidatorSol from "./UniversalSignatureValidator.sol";
export type { universalSignatureValidatorSol };
