version: 2.1

orbs:
  slack: circleci/slack@3.4.2

jobs:
  e2e-tests:
    working_directory: ~/x
    docker:
      - image: cypress/included:cypress-13.15.1-node-20.18.0-chrome-130.0.6723.69-1-ff-131.0.3-edge-130.0.2849.52-1
    resource_class: xlarge
    steps:
      - checkout

      - run:
          name: Install jq
          command: apt-get update && apt-get install -y curl jq

      # 1) Clone the e2e repo
      - run:
          name: Clone e2e‑sdk‑prime repository
          command: |
            cd ~
            git clone -b master --single-branch https://$GITHUB_TOKEN@github.com/etherspot/e2e-sdk-prime.git
            cd e2e-sdk-prime
            ls -la
            
            if [ "$CIRCLE_BRANCH" = "main" ]; then
              echo "PRIVATE_KEY=$PRIVATE_KEY_MAINNET" > .env
              echo "PROJECT_KEY=$PROJECT_KEY_MAINNET" >> .env
              echo "API_KEY=$API_KEY_MAINNET" >> .env
              echo "API_KEY_ARKA=$API_KEY_ARKA_MAINNET" >> .env
              echo "API_KEY_SESSIONKEY=$API_KEY_SESSIONKEY_MAINNET" >> .env
              echo "INCORRECT_API_KEY_ARKA=$INCORRECT_API_KEY_ARKA_MAINNET" >> .env
              echo "INVALID_API_KEY_ARKA=$INVALID_API_KEY_ARKA_MAINNET" >> .env
              echo "BUNDLER_API_KEY=$BUNDLER_API_KEY_MAINNET" >> .env
              echo "DATA_API_KEY=$DATA_API_KEY_MAINNET" >> .env
            else
              echo "PRIVATE_KEY=$PRIVATE_KEY_TESTNET" > .env
              echo "PROJECT_KEY=$PROJECT_KEY_TESTNET" >> .env
              echo "API_KEY=$API_KEY_TESTNET" >> .env
              echo "API_KEY_ARKA=$API_KEY_ARKA_TESTNET" >> .env
              echo "API_KEY_SESSIONKEY=$API_KEY_SESSIONKEY_TESTNET" >> .env
              echo "INCORRECT_API_KEY_ARKA=$INCORRECT_API_KEY_ARKA_TESTNET" >> .env
              echo "INVALID_API_KEY_ARKA=$INVALID_API_KEY_ARKA_TESTNET" >> .env
              echo "BUNDLER_API_KEY=$BUNDLER_API_KEY_TESTNET" >> .env
              echo "DATA_API_KEY=$DATA_API_KEY_TESTNET" >> .env
            fi
            npm install --legacy-peer-deps
            npx playwright install --with-deps

            if [ "$CIRCLE_BRANCH" == "main" ]; then
              echo "Running mainnet tests"
              npm run test-mainnet-combined
            else
              echo "Running testnet tests"
              npm run test-testnet-combined
            fi

      # 3) Install dependencies & run the tests
      # - run:
      #     name: Checkout e2e-sdk-prime repo and run tests
      #     no_output_timeout: 90m
      #     command: |
      #       cd ~/e2e-sdk-prime
      #       rm -rf package-lock.json
      #       npm install 
      #       npx playwright install --with-deps

      #       if [ "$CIRCLE_BRANCH" == "main" ]; then
      #         echo "Running mainnet tests"
      #         npm run test-mainnet-combined
      #       else
      #         echo "Running testnet tests"
      #         npm run test-testnet-combined
      #       fi

      - run:
          name: Move test report
          when: always
          command: |
            mv /root/e2e-sdk-prime/mochawesome-report /tmp/
            chmod 777 -R /tmp/mochawesome-report

      - store_artifacts:
          path: /tmp/mochawesome-report
          when: always

      - run:
          name: Parse and send test results to Slack
          when: always
          command: |
            wget https://output.circle-artifacts.com/output/job/${CIRCLE_WORKFLOW_JOB_ID}/artifacts/${CIRCLE_NODE_INDEX}/tmp/mochawesome-report/mochawesome.json

            MOCHAWESOME_JSON_FILE=./mochawesome.json
            FAILED_TESTS_FILE=failed-tests.txt
            TOTAL_SUITES=$(jq '.stats.suites' $MOCHAWESOME_JSON_FILE)
            TOTAL_PASSES=$(jq '.stats.passes' $MOCHAWESOME_JSON_FILE)
            TOTAL_PENDING=$(jq '.stats.pending' $MOCHAWESOME_JSON_FILE)
            TOTAL_FAILURES=$(jq '.stats.failures' $MOCHAWESOME_JSON_FILE)
            START_TIME=$(jq -r '.stats.start' $MOCHAWESOME_JSON_FILE)
            END_TIME=$(jq -r '.stats.end' $MOCHAWESOME_JSON_FILE)
            DURATION_MS=$(jq -r '.stats.duration' $MOCHAWESOME_JSON_FILE)

            START_TIME_FORMATTED=$(date -d "$START_TIME" "+%Y-%m-%d %H:%M:%S")
            END_TIME_FORMATTED=$(date -d "$END_TIME" "+%Y-%m-%d %H:%M:%S")
            DURATION_MIN=$(awk "BEGIN {printf \"%.2f\",${DURATION_MS}/60000}")

            jq -r '.results[] | .suites[] | select(.failures > 0) | {suite: .title, tests: [.tests[] | select(.fail) | .title]} | select(.tests | length > 0) |
            "*Suite:* \(.suite)\n*Failing Tests:* \n\(.tests | map("- " + .) | join("\n"))\n"' $MOCHAWESOME_JSON_FILE > $FAILED_TESTS_FILE

            if [ -s $FAILED_TESTS_FILE ]; then
              MESSAGE=$(cat $FAILED_TESTS_FILE)
              SLACK_MESSAGE=":x: *ETHERSPOT_PRIME_SDK UI Tests Failed :x: *\n\
            *Project:* ${CIRCLE_PROJECT_REPONAME}\n\
            *Triggered by:* ${CIRCLE_USERNAME}\n\
            *Branch:* ${CIRCLE_BRANCH}\n\
            *Commit:* <https://github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/commit/${CIRCLE_SHA1}|${CIRCLE_SHA1}>\n\n\
            *Test Summary:*\n\
            *Total Suites:* ${TOTAL_SUITES}\n\
            *Passes:* ${TOTAL_PASSES}\n\
            *Pending:* ${TOTAL_PENDING}\n\
            *Failures:* ${TOTAL_FAILURES}\n\
            *Start Time:* ${START_TIME_FORMATTED}\n\
            *End Time:* ${END_TIME_FORMATTED}\n\
            *Duration:* ${DURATION_MIN} minutes\n\n\
            *Failed Tests:*\n${MESSAGE}\n\
            *Report:* <https://output.circle-artifacts.com/output/job/${CIRCLE_WORKFLOW_JOB_ID}/artifacts/${CIRCLE_NODE_INDEX}/tmp/mochawesome-report/mochawesome.html|View HTML Report>\n\
            *Job:* <https://circleci.com/gh/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/${CIRCLE_BUILD_NUM}|View Job>\n\
            cc: ${TAG_RESPONSIBLE_PEOPLE}"
            else
              SLACK_MESSAGE=":white_check_mark: All ETHERSPOT_PRIME_SDK UI tests passed\n\
            *Project:* ${CIRCLE_PROJECT_REPONAME}\n\
            *Triggered by:* ${CIRCLE_USERNAME}\n\
            *Branch:* ${CIRCLE_BRANCH}\n\
            *Commit:* <https://github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/commit/${CIRCLE_SHA1}|${CIRCLE_SHA1}>\n\
            *Job:* <https://circleci.com/gh/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/${CIRCLE_BUILD_NUM}|View Job>\n\
            \n*Test Summary:*\n\
            *Total Suites:* ${TOTAL_SUITES}\n\
            *Passes:* ${TOTAL_PASSES}\n\
            *Pending:* ${TOTAL_PENDING}\n\
            *Failures:* ${TOTAL_FAILURES}\n\
            *Start Time:* ${START_TIME_FORMATTED}\n\
            *End Time:* ${END_TIME_FORMATTED}\n\
            *Duration:* ${DURATION_MIN} minutes\n\n\
            *Report:* <https://output.circle-artifacts.com/output/job/${CIRCLE_WORKFLOW_JOB_ID}/artifacts/${CIRCLE_NODE_INDEX}/tmp/mochawesome-report/mochawesome.html|View HTML Report>\n\
            *Job:* <https://circleci.com/gh/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/${CIRCLE_BUILD_NUM}|View Job>"
            
            fi

            curl -X POST -H 'Content-type: application/json' --data '{"text":"'"$SLACK_MESSAGE"'"}' $E2E_SLACK_WEBHOOK_URL

workflows:
  version: 2

  run-on-commit:
    jobs:
      - e2e-tests:
          filters:
            branches:
              only:
                - main
                - develop
                - PRO-3477-e2e
