version: 2.1

parameters:
  run_e2e_tests:
    type: boolean
    default: true

jobs:
  install:
    working_directory: ~/etherspot-prime-sdk
    docker:
      - image: cimg/node:18.16.1
    steps:
      - checkout

      - run:
          name: Install Bun
          command: |
            curl -fsSL https://bun.sh/install | bash
            echo 'export BUN_INSTALL="$HOME/.bun"' >> $BASH_ENV
            echo 'export PATH="$BUN_INSTALL/bin:$PATH"' >> $BASH_ENV
            source $BASH_ENV

      - run:
          name: Authenticate npm
          command: echo "//registry.npmjs.org/:_authToken=$ETHERSPOT_NPM_TOKEN" > ~/.npmrc

      - run:
          name: Install dependencies
          command: bun install

      - run:
          name: Build SDK
          command: bun run build

      - run:
          name: Pack SDK as tarball
          command: |
            npm pack
            mv etherspot-prime-sdk-*.tgz /tmp/prime-sdk.tgz

      - persist_to_workspace:
          root: /
          paths:
            - tmp/prime-sdk.tgz

  e2e-tests:
    docker:
      - image: cimg/node:18.16.1
    steps:
      - attach_workspace:
          at: /

      - run:
          name: Checkout E2E repo
          command: |
            cd ~
            git clone https://github.com/etherspot/e2e-sdk-prime.git

      - run:
          name: Configure E2E environment
          command: |
            cd ~/e2e-sdk-prime
            sed -i.bak "s/private_key/$PRIVATE_KEY/g" .env
            sed -i.bak "s/project_key/$PROJECT_KEY/g" .env
            sed -i.bak "s/project_key_testnet/$PROJECT_KEY_TESTNET/g" .env
            sed -i.bak "s/api_key/$API_KEY/g" .env
            sed -i.bak "s/api_key_arka/$API_KEY_ARKA/g" .env
            sed -i.bak "s/incorrect_api_key/$INCORRECT_API_KEY/g" .env
            sed -i.bak "s/incorrect_api_key_arka/$INCORRECT_API_KEY_ARKA/g" .env
            sed -i.bak "s/invalid_api_key/$INVALID_API_KEY/g" .env
            sed -i.bak "s/invalid_api_key_arka/$INVALID_API_KEY_ARKA/g" .env
            sed -i.bak "s/bundler_api_key/$BUNDLER_API_KEY/g" .env
            sed -i.bak "s/data_api_key/$DATA_API_KEY/g" .env

      - run:
          name: Install SDK + E2E dependencies
          command: |
            cd ~/e2e-sdk-prime
            npm install /tmp/prime-sdk.tgz --legacy-peer-deps
            npm install --legacy-peer-deps

      - run:
          name: Run E2E tests
          no_output_timeout: 60m
          command: |
            cd ~/e2e-sdk-prime
            npm run test-mainnet-combined

      - run:
          name: Collect test report
          when: always
          command: |
            if [ -d "/home/circleci/e2e-sdk-prime/mochawesome-report" ]; then
              mv /home/circleci/e2e-sdk-prime/mochawesome-report /tmp/
            else
              echo "mochawesome-report not found"
            fi

      - store_artifacts:
          path: /tmp/mochawesome-report
          when: always

  publish-npm-package:
    working_directory: ~/etherspot-prime-sdk
    docker:
      - image: cimg/node:18.16.1
    steps:
      - checkout

      - run:
          name: Install Bun
          command: |
            curl -fsSL https://bun.sh/install | bash
            echo 'export BUN_INSTALL="$HOME/.bun"' >> $BASH_ENV
            echo 'export PATH="$BUN_INSTALL/bin:$PATH"' >> $BASH_ENV
            source $BASH_ENV

      - run:
          name: Authenticate npm
          command: echo "//registry.npmjs.org/:_authToken=$ETHERSPOT_NPM_TOKEN" > ~/.npmrc

      - run:
          name: Install & Build
          command: |
            bun install
            bun run build

      - run:
          name: Publish package
          command: bun publish --access public

workflows:
  version: 2.1
  install_and_publish:
    jobs:
      - install
      - e2e-tests:
          requires:
            - install
      - publish-npm-package:
          requires:
            - e2e-tests
          filters:
            branches:
              only: update-circleci
