/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../../../common";
import type {
  ErrorsLib,
  ErrorsLibInterface,
} from "../../../../src/ERC7579/libraries/ErrorsLib";

const _abi = [
  {
    inputs: [],
    name: "AddingInvalidGuardian",
    type: "error",
  },
  {
    inputs: [],
    name: "AddingInvalidOwner",
    type: "error",
  },
  {
    inputs: [],
    name: "AlreadySignedProposal",
    type: "error",
  },
  {
    inputs: [],
    name: "InvalidProposal",
    type: "error",
  },
  {
    inputs: [],
    name: "NotEnoughGuardians",
    type: "error",
  },
  {
    inputs: [],
    name: "OnlyGuardian",
    type: "error",
  },
  {
    inputs: [],
    name: "OnlyOwnerOrGuardianOrSelf",
    type: "error",
  },
  {
    inputs: [],
    name: "OnlyOwnerOrSelf",
    type: "error",
  },
  {
    inputs: [],
    name: "ProposalResolved",
    type: "error",
  },
  {
    inputs: [],
    name: "ProposalTimelocked",
    type: "error",
  },
  {
    inputs: [],
    name: "ProposalUnresolved",
    type: "error",
  },
  {
    inputs: [],
    name: "RemovingInvalidGuardian",
    type: "error",
  },
  {
    inputs: [],
    name: "RemovingInvalidOwner",
    type: "error",
  },
  {
    inputs: [],
    name: "WalletNeedsOwner",
    type: "error",
  },
] as const;

const _bytecode =
  "0x60566037600b82828239805160001a607314602a57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea26469706673582212208d77a094057176932190cc82a0949e5656ae0e3c73149fc8a0e34e957dade28d64736f6c63430008170033";

type ErrorsLibConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: ErrorsLibConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class ErrorsLib__factory extends ContractFactory {
  constructor(...args: ErrorsLibConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ErrorsLib> {
    return super.deploy(overrides || {}) as Promise<ErrorsLib>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): ErrorsLib {
    return super.attach(address) as ErrorsLib;
  }
  override connect(signer: Signer): ErrorsLib__factory {
    return super.connect(signer) as ErrorsLib__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): ErrorsLibInterface {
    return new utils.Interface(_abi) as ErrorsLibInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ErrorsLib {
    return new Contract(address, _abi, signerOrProvider) as ErrorsLib;
  }
}
