/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { UniversalSigValidator } from "./UniversalSigValidator";
export type { ValidateSigOffchain } from "./ValidateSigOffchain";
