/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as iEtherspotPaymasterSol from "./IEtherspotPaymaster.sol";
export type { iEtherspotPaymasterSol };
export type { IWhitelist } from "./IWhitelist";
